version: "3.7"

services: 
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    container_name: owl-db
  core:
    build: .
    command: npm run test
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/app
    depends_on:
      - mongo
    container_name: owl-core
